---
Name: silvershop-shipping
---

SilverShop\Tasks\PopulateShopTask:
  extensions:
    - SilverShop\Shipping\Tasks\PopulateShopTableShippingTask
SilverShop\Model\Order:
  extensions:
    - SilverShop\Shipping\Extension\OrderShippingExtension
SilverShop\Page\CartPageController:
  extensions:
    - SilverShop\Shipping\Extension\CartPageShippingExtension
