---
Name: shopshippingconfig
After: shop/*
---

PopulateShopTask:
  extensions:
    - PopulateShopTableShippingTask
Order:
  extensions:
    - OrderShippingExtension
CartPage_Controller:
  extensions:
    - CartPageShippingExtension
